variables:
  NODE_VERSION: "18"

image: node:${NODE_VERSION}

stages:
  - unit_tests

unit_tests:
  stage: unit_tests
  tags:
    - local
    - docker
  variables:
    POSTGRES_DB: test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    NODE_ENV: ci

  services:
    - name: postgres:alpine

  before_script:
    - npm ci
    - cd ./packages/server
    - npm run ci:migrate
    - npm start
  script:
    - npm run test:unit
  artifacts:
    when: always
    reports:
      junit: ./junit.xml
    paths:
      - ./allure-results
