create role client with login noinherit encrypted password 'sf2nce3' connection limit -1;
create role worker with login inherit encrypted password '1gjg5cjk' connection limit -1;
create role admin with login noinherit createdb createrole encrypted password '2jk493hs' connection limit -1;

grant insert, update, select on table public.user to client;
grant usage, select on sequence user_id_seq to client;
grant insert, select on table public.order to client;
grant usage, select on sequence order_id_seq to client;
grant select on table public.order_status to client;
grant insert, select on table public.order__product to client;
grant select on table public.product to client;
grant select on table public.product__shop to client;
grant select on table public.manufacturer to client;
grant select on table public.country to client;
grant select on table public.company to client;
grant select on table public.shop to client;
grant select on table public.user__company to client;
grant insert, delete, select on table public.session to client;

grant client to worker;
grant delete on table public.user to worker;
grant update on table public.order to worker;
grant insert, update, delete, select on table public.company to worker;
grant usage, select on sequence company_id_seq to worker;
grant insert, update, delete, select on table public.user__company to worker;
grant update, delete  on table public.order__product to worker;
grant insert, update, delete, select on table public.product__shop to worker;

grant insert, update, delete, select on table public.user to admin;
grant usage, select on sequence user_id_seq to admin;
grant insert, update, delete, select on table public.order to admin;
grant usage, select on sequence order_id_seq to admin;
grant update, delete, select on table public.order__product to admin;
grant insert, update, delete, select on table public.product to admin;
grant usage, select on sequence product_id_seq to admin;
grant insert, update, delete, select on table public.product__shop to admin;
grant insert, delete, select on table public.session to admin;
grant insert, update, delete, select on table public.company to admin;
grant usage, select on sequence company_id_seq to worker;
grant insert, update, delete, select on table public.user__company to admin;
grant insert, update, delete, select on table public.country to admin;
grant usage, select on sequence country_id_seq to admin;
grant insert, update, delete, select on table public.manufacturer to admin;
grant usage, select on sequence manufacturer_id_seq to admin;
grant insert, update, delete, select on table public.shop to admin;
grant usage, select on sequence shop_id_seq to admin;
grant insert, update, delete, select on table public.order_status to admin;
grant usage, select on sequence order_status_id_seq to admin;